<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use App\Post;
use App\User;
use App\http\Requests\PostRequest;
use GuzzleHttp\Client;

class DatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
        factory(\App\User::class)->create(['name'=>'admin', 'email'=>'admin@admin.com']);
        factory(\App\User::class, 20)->create();
        factory(\App\Blog::class, 1)->create();
        factory(\App\Blog::class)->create(['name'=>'API BLOG',	'description'=>'This blog has been generated by the api provided']);
        factory(\App\Post::class, 100)->create(['blog_id'=>1,'num_likes'=>0]);

        $client = new Client([
            'base_uri' => 'https://sq1-api-test.herokuapp.com/',
        ]);
        $response = $client->request('GET', 'https://sq1-api-test.herokuapp.com/posts');
        $apis=(json_decode($response->getBody()->getContents()))->data;

        foreach ($apis as $api) {
            DB::table('posts')->insert([
                'blog_id'=>2,
                'user_id'=>1,
                'title'=>$api->title,
                'description'=>$api->description,
                'publication_date'=>$api->publication_date,
                'num_likes'=>0
            ]);
        }
    }
}
